all:
	dune build

cp_inter:
	cp intermediate_graph.ml /home/sven/Documents/ENS/reactif/reactif_mini_jazz/extended_mini_jazz/representation/intermediate_graph.ml
	cp mk_intermediate.ml /home/sven/Documents/ENS/reactif/reactif_mini_jazz/extended_mini_jazz/representation/mk_intermediate.ml
	cp graph_utils.ml /home/sven/Documents/ENS/reactif/reactif_mini_jazz/extended_mini_jazz/representation/graph_utils.ml
	cp intermediate_to_kgraph.ml /home/sven/Documents/ENS/reactif/reactif_mini_jazz/extended_mini_jazz/representation/intermediate_to_kgraph.ml

